### ISSUE TITLE
After re-installation, the friend list is sometimes broken

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-ios-client#103]
Happens sometimes on re-installation or on new installation of an app with multiple auto-connected services.

The friends are in the friendSet, but not in the friends table. You can't connect to them because then the server responds with "you are already friends with xxx"

**Comment by bart-at-mobicage** [comment]
When testing, try to connect to 5 services at a time to see if they are all connected successfully. 
Repeat this 5 times.

**Comment by RubenMattan** [comment]
Thats works as well
