### ISSUE TITLE
Regenerate all DEV provisioning profiles

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-ios-client#108]
They were regenerated using `fastlane match` when the developer cert expired. However, there's something wrong with them. Code signing doesn't work.
Regenerate them all using `fastlane sigh`. See the `create_provisioning_profiles` lane in  `Fastfile_template.rb` in the `apps` repo.

**Comment by lucasvanhalst** [comment]
Check code from old scripts and what the difference in arguments is with how they are created now

**Comment by lucasvanhalst** [comment]
Done
