### ISSUE TITLE
News text encode incorrect

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-ios-client#113]
![screen shot 2017-07-14 at 13 57 50](https://user-images.githubusercontent.com/1122760/28211365-86224498-689c-11e7-8002-5f674df0fe96.png)

**Comment by bart-at-mobicage** [comment]
It's seems it are emoticons which should be available on iOS

![screen shot 2017-07-20 at 14 36 06](https://user-images.githubusercontent.com/17762105/28418477-1d219808-6d5c-11e7-8ee8-4c479aac7ff1.png)

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-ios-client#40
