### ISSUE TITLE
PIN code needed when opening secure app [16h]

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-ios-client#117]
Make it possible that an app-wide private key is created right after the registration process.
The name and algorithm must come from the build constants.

Every time the user opens the app, he must enter his pin code in order to be able to use his app.

The way keys are stored and generated is changed, so the obj-c code must be updated to reflect the changes done on Android  as well.

**Comment by RubenMattan** [comment]
We are going to put a 3min delay on entering the pin again
