### ISSUE TITLE
Unable to set pin because pin was already set

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-ios-client#150]
- There was no back button (#149) in the import key so they killed the app. From there they wanted to generate a key pair but that doesn't work because askpin is triggered before create keypair (eternal wait for enter pin)

- Setup pin screen should not have a done button

- Also is should be better if generate/import is a view instead of a popup (doens't make sense to see setup pin when pin was already set)

**Comment by bart-at-mobicage** [comment]
Still valid?

**Comment by RubenMattan** [comment]
You are not stuck anymore. However the other issues are not fixed.
- There is still a done button on setup pin
- You still see setup pin in the background even when pin was already set.

**Comment by bart-at-mobicage** [comment]
- [ ] Also, in the setup pin VC when you push "import existing", then "cancel" and generate new key, then in the next screen there is no "Done" button on the Security page.
