### ISSUE TITLE
build job stored the wrong app_id for be-diksmuide and be-halen

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-ios-client#160]
The app_id that was stored looked like a guid. It's been fixed in the mean time, but investigate the build jobs to see what happened.

**Comment by lucasvanhalst** [comment]
Build logs look fine

halen: 
I, [2017-09-04T16:15:47.406083 #57978]  INFO -- : iOS app id: 1278489711
INFO:root:Sending iOS app id 1278489711 to https://rogerth.at/bob/api/apps/set_ios_app_id

diksmuide

[10:02:24]: [iTC] App 'com.mobicage.rogerthat.be-diksmuide' already exists (1245249672), nothing to do on iTunes Connect
I, [2017-07-26T10:02:25.232986 #97991]  INFO -- : iOS app id: 1245249672
INFO:root:Sending iOS app id 1245249672 to https://rogerth.at/bob/api/apps/set_ios_app_id
