### ISSUE TITLE
Check if access to the camera is granted when using UIImagePicker

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-ios-client#172]
See `checkScanningSupportedInVC` in `MCTScannerVC`. Make this method re-usable (customize the popup message and error message. 

Search for `showPickerWithSourceType:UIImagePickerControllerSourceTypeCamera` to see where to add the check.

**Comment by RubenMattan** [comment]
Why is this change needed?

**Comment by RubenMattan** [comment]
Can't dev against real devices.
