### ISSUE TITLE
P2P chat shouldn't show myself in the title

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-ios-client#18]
Happened when sending to 1 friend
Test multiple friends as well

![screen shot 2016-11-18 at 10 52 32](https://cloud.githubusercontent.com/assets/17762105/20426847/419478b8-ad81-11e6-85e8-04aa42ba4134.png)

**Comment by RubenMattan** [comment]
Message list should also filter out yourself
![screen shot 2016-12-14 at 13 17 46](https://cloud.githubusercontent.com/assets/1122760/21181751/b96805ac-c1ff-11e6-849a-e892ab46c526.png)
