### ISSUE TITLE
Multiple news feeds

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-ios-client#186]
A `feed_name` to distinguish feeds. `None` means the default News Feed.
`feed_name` is added to `NewsItemTO` and `GetNewsRequestTO`.

- [ ] Add column `feed_name` to the `news_item` table
- [ ] Add `params` (dict) to HomeScreenItem
  - HomeScreenItem with action `news` can optionally have param `feed_name`. Eg. `{"feed_name": "my-random-feed-name"}`  
  - HomeScreenItem with action `services` (and variants) can optionally have param `collapse`. Eg. `{"collapse": true}`

**Comment by RubenMattan** [comment]
already done see https://github.com/rogerthat-platform/rogerthat-ios-client/pull/206
