### ISSUE TITLE
Opening news feed from cordova/html5 branding

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-ios-client#220]
Looks like `feed_name` param is not implemented in `openNavigationItemWithResultHandler:params:`. Maybe best to refactor collapse/feed_name in this use case into a `params` dict.

**Comment by bart-at-mobicage** [comment]
When using the params dict, we won't need to change this code in the future. And this will automatically work as well:

```
rogerthat.util.open({
    action_type: "click",
    action: "xxx",
    params: {
        service_email: "service-c4dcf31a-8c43-4bfd-ac25-4f5dc5e908c4@rogerth.at"
    }
});
```

```
rogerthat.util.open({
    action_type: "open",
    action: "app",
    params: {
        android_app_id: "...",
        android_scheme: "xxx://",
        ios_app_id: "...",
        ios_scheme: "xxx://"
    }
});
```

These 3 use cases are needed soon in a city-app with custom home branding.

**Comment by RubenMattan** [comment]
https://github.com/rogerthat-platform/rogerthat-ios-client/pull/221
