### ISSUE TITLE
GDPR - Registration procedure changes

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-ios-client#228]
- [ ] Disable iBeacon support
- [ ] Don't show location step
- Step 1
  - [ ] Hide the 'read TOS' link
  - [ ] Rename button to 'Start'
- [ ] Step 2: TOS page in 1 giant scrollview
  - TOS
  - Checkbox: I am older than 16 years
  - Agree
  - In case checkbox not selected, show popup
    - Checkbox: I am the person who bears parental responsibility for the child, and I give permission to the child to use this app.
      - NL: Ik ben de persoon die de ouderlijke verantwoordelijkheid voor het kind draagt, en ik geef de toestemming aan het kind om deze app te gebruiken.
- [ ] Step 3: Notifications

> XXX is een app waarmee u kan communiceren met personen en organisaties. Deze communicatie gebeurt via berichten. De XXX app gebruikt notificaties om u op de hoogte te houden van nieuwe berichten. Daarom is het belangrijk om notificaties toe te staan voor de XXX app.
> 
> Er zijn 3 soorten berichten:
> 1. Berichten die specifiek gericht zijn aan jou. Deze kunnen komen van vrienden of van organisaties (bijvoorbeeld informatie over een bestelling of een antwoord op een vraag).
> 2. Nieuws, info en evenementen vanuit de stad of gemeente.
> 3. Nieuws, info en evenementen van de handelaars en verenigingen die je volgt.
> 
> [ Verder ]

**Comment by RubenMattan** [comment]
matches android
