### ISSUE TITLE
Show that contacts are used to auto-complete the e-mail address

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/rogerthat-ios-client#237]
An app was rejected for this:

Guideline 5.1.2 - Legal - Privacy - Data Use and Sharing

Your app accesses user data from the device but does not have the required precautions in place.

Specifically, permission modal alert does not clarify if their information will be uploaded to the server.

Next Steps

To collect personal data with your app, you must make it clear to the user that their personal data will be uploaded to your server and you must obtain the user's consent before the data is uploaded. You must also have a Privacy Policy URL and ensure that the URL you provide directs users to your privacy policy.

- Starting with iOS 6, there are keys for specifying the reason the app will access the user's protected data. When the access prompt is displayed, the purpose specified in these keys is displayed in that dialog box. If your app will be transmitting protected user data, the usage string in your access request should clearly inform the user that their data will be uploaded to your server if they consent.

Resources

For more information on these keys, please review the Information Property List Key Reference https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#/apple_ref/doc/uid/TP40009251-SW1.

![screenshot-0523-102848](https://user-images.githubusercontent.com/6652304/40484688-c40235ea-5f5c-11e8-8cfb-ffaae1848907.png)

**Comment by RubenMattan** [comment]
Going to comment this for now

**Comment by bart-at-mobicage** [comment]
Guideline 5.1.2 - Legal - Privacy - Data Use and Sharing


Your app accesses user data from the device but does not have the required precautions in place.

Specifically, the permission modal alert does not clarify if the user’s contact information will be uploaded to the server.

Next Steps

To collect personal data with your app, you must make it clear to the user that their personal data will be uploaded to your server and you must obtain the user's consent before the data is uploaded. You must also have a Privacy Policy URL and ensure that the URL you provide directs users to your privacy policy.

- Starting with iOS 6, there are keys for specifying the reason the app will access the user's protected data. When the access prompt is displayed, the purpose specified in these keys is displayed in that dialog box. If your app will be transmitting protected user data, the usage string in your access request should clearly inform the user that their data will be uploaded to your server if they consent.

Resources

For more information on these keys, please review the [Information Property List Key Reference.](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#/apple_ref/doc/uid/TP40009251-SW1)

<img width="375" alt="attachment-2537302474411413796screenshot_0525_192917" src="https://user-images.githubusercontent.com/17762105/40602596-77f543e0-6259-11e8-96e6-ddbb4338fcfd.png">

**Comment by RubenMattan** [comment]
Works on Bart his phone as well, maybe they complain about contacts from phone book

**Comment by RubenMattan** [comment]
Updated in https://github.com/rogerthat-platform/rogerthat-ios-client/commit/5282eec3778e511e3dd588f2bca0552035b5c9fd

Will start a new job
