### ISSUE TITLE
Profile name is hidden under navigation bar

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-ios-client#26]
Happened for `anthony@mobicage.com:be-herzele` around `Mon 21 Nov 2016 11:19:59 GMT`

![img_0734](https://cloud.githubusercontent.com/assets/17762105/20487353/49a97e0c-b003-11e6-80aa-80aeee0d45e4.PNG)

**Comment by RubenMattan** [comment]
i also noticed that afterwards the drawer does not open
