### ISSUE TITLE
news item doesn't show the image

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-ios-client#48]
![screen shot 2016-11-30 at 12 13 01](https://cloud.githubusercontent.com/assets/1122760/20750326/79e8d10e-b6f6-11e6-9f80-899a0fe628e7.png)

**Comment by bart-at-mobicage** [comment]
maybe we need to extend TTImageView and add a retry mechanism in the download code.

**Comment by RubenMattan** [comment]
I don't think its related to a download. i closed the vc and opened it again but still no image

**Comment by RubenMattan** [comment]
Occurred because the image was bigger then 150kb
