### ISSUE TITLE
Swipable area is reduced in service home screen

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-ios-client#59]
Swiping to left/right is not possible anymore underneath the icons (the red area). Increase the height of this scroll view such that swiping is working again.

![img_3922](https://cloud.githubusercontent.com/assets/17762105/21566916/0a3e5788-cea8-11e6-83b5-1482fc9be896.PNG)

**Comment by RubenMattan** [comment]
Can't reproduce
