### ISSUE TITLE
Message list slide to delete does not return to editing false

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-ios-client#6]
This only occurred when not fully sliding to delete the message

![screen shot 2016-10-28 at 10 00 01](https://cloud.githubusercontent.com/assets/1122760/19799144/58f2975c-9cf5-11e6-9c69-3c9250dfd5dc.png)

![screen shot 2016-10-28 at 10 00 07](https://cloud.githubusercontent.com/assets/1122760/19799145/5b4aadf0-9cf5-11e6-8a62-a3a5cd66583c.png)

**Comment by RubenMattan** [comment]
Safari has the same issue with is history...

**Comment by RubenMattan** [comment]
We can use a library however i would not fix this issue.

https://github.com/MortimerGoro/MGSwipeTableCell

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-ios-client#41
