### ISSUE TITLE
Toolbar not hidden after viewing image

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-ios-client#93]
Scenario
- You need to have a service with a chat that includes a message with an image attachment.
- That service also needs to have a news item.
- click the news item to go to the service menu
- open messages
- open the chat and click the image
- go back a few times until you reach the news feed again (I swiped from the ledge edge to go back)
- the news feed will now have a toolbar

**Comment by bart-at-mobicage** [comment]
![img_4112](https://cloud.githubusercontent.com/assets/17762105/25770823/0ab754de-3240-11e7-8ac5-66b0ab37dbdb.PNG)

**Comment by RubenMattan** [comment]
Already fixed by https://github.com/rogerthat-platform/rogerthat-ios-client/issues/82
