### ISSUE TITLE
Jenkins: Remove Xcode plugin and use fastlane

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-ios-client#96]
The automated iOS builds are broken since the slaves updated Xcode to 8.3 (https://issues.jenkins-ci.org/browse/JENKINS-43163)
- Let's get rid of the jenkins plugin and replace by fastlane commands like mentioned in [Jenkins Jira](https://issues.jenkins-ci.org/browse/JENKINS-43163?focusedCommentId=299209&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-299209)
  - You can continue working on `fastlane_ios` branch on the `apps` repo.
  - Add a `fastlane gym` step to the `fastFile`
    - https://github.com/fastlane/fastlane/tree/master/gym

_______

- [x] Clone the iOS-1-App job from jenkins.mobicage.com to a new one such that you can test easier
- [x] Replace the Xcode jenkins step by `fastlane gym`
- [x] Use `fastlane cert` or `fastlane match` to store the Developer and Release certificates into a **_private_**(!!) git repo such that new build slaves don't need to be configured manually
  - see ~/Desktop/Certificates.p12

**Comment by LeeSmet** [comment]
2 more things need to be done:
1. Manually encrypt and upload the GIG and Mobitrain certs to the certificate repo on gitlab in new branches
2. Fix the unit test to create screenshots as it fails hard on jenkins.

To encrypt the certificates, their respective ids from the apple dev portal needs to be known. This requires bart to accept the new license agreement manually on the portal. The ids can then be listed with the following ruby script:
```ruby
require 'spaceship'

Spaceship.login('bart@mobicage.com')
Spaceship.select_team

Spaceship.certificate.all.each do |cert| 
  cert_type = Spaceship::Portal::Certificate::CERTIFICATE_TYPE_IDS[cert.type_display_id].to_s.split("::")[-1]
  puts "Cert id: #{cert.id}, name: #{cert.name}, expires: #{cert.expires.strftime("%Y-%m-%d")}, type: #{cert_type}"
end
```

This prints all certs for the respective team. The correct production and dev certificates must then be found by comparing the expiration date with the ones in the keychain. When the correct production and development certificate is identified, and their ids are known, it can be exported from the keychain and encrypted.

For every cert from the keychain, export it to `certificate.p12` and `certificate.pem`. Don't set a password for the p12 file. Then run the following openssl commands:

```bash
openssl pkcs12 -nocerts -nodes -out key.pem -in certificate.p12

openssl aes-256-cbc -k REPO-PASSWORD -in key.pem -out CERT_ID.p12 -a
openssl aes-256-cbc -k REPO-PASSWORD -in certificate.cer -out CERT_ID.cer -a
```
replace `CERT_ID` with the certificate id retrieved through the previous script. The `REPO-PASSWORD` can be found in the `ios-fastlane` job in jenkins. Now move these to either the `certs/development` or `certs/distribution` directory, depending on whether this is a dev or production certificate. The branch is supposed to be the `team id`( can be seen in the certificate name in the keychain). Make sure to remove any already exisiting certificates after branching.

**Comment by bart-at-mobicage** [comment]
Created new ticket for the UI tests thing
